version: "3.9"

services:

  db:
    container_name: db
    image: postgis/postgis:15-master
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/capital:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=capital
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db


  backend:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    env_file: matrix_converter/.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    restart: on-failure